name: Build Chip No Version

on:
  push:
  workflow_dispatch:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
      - name: Build chip
        uses: wokwi/wokwi-chip-clang-action@main
        with:
          sources: "src/chip-moduleLN298.chip.c"
      - name: Copy chip.json
        run: sudo cp src/chip-moduleLN298.chip.json dist/chip.json
      - name: 'Upload Artifacts'
        uses: actions/upload-artifact@v4
        with:
          name: chip
          path: |
            dist/chip.json
            dist/chip.wasm
      - name: Create Tag
        # Uses the workflow run number to create a unique tag name
        run: |
          TAG_NAME="v${{ github.run_number }}"
          git tag -a $TAG_NAME -m "Release $TAG_NAME"
          git push origin $TAG_NAME
          with:
          token: ${{ secrets.GITHUB_TOKEN }}

  # The release job only runs when you push a tag starting with "v", e.g. v1.0.0 
  release:
    name: Release
    needs: build
    if: github.event_name == 'push' 
    runs-on: ubuntu-latest
    steps:
      - name: Download compiled chip
        uses: actions/download-artifact@v4
        with:
          name: chip
          path: chip
      - name: Create a zip archive
        run: cd chip && zip -9 ../chip.zip chip.*
        env:
          ZIP_VERSION: ${{ github.ref_name }}
      - name: Upload release
        uses: ncipollo/release-action@v1
        with:
          artifacts: chip.zip
          token: ${{ secrets.GITHUB_TOKEN }}
          generateReleaseNotes: true
          skipIfReleaseExists: true
          allowUpdates: true 
